export const General = [
 {
   	header: 'Dynamics of Opinion Forming in Structurally Balanced Social Networks',
   	abstract: 'A structurally balanced social network is a social community that splits into two antagonistic factions (typical example being a two-party political system). The process of opinion forming on such a community is most often highly predictable, with polarized opinions reflecting the bipartition of the network. The aim of this paper is to suggest a class of dynamical systems, called monotone systems, as natural models for the dynamics of opinion forming on structurally balanced social networks. The high predictability of the outcome of a decision process is explained in terms of the order-preserving character of the solutions of this class of dynamical systems. If we represent a social network as a signed graph in which individuals are the nodes and the signs of the edges represent friendly or hostile relationships, then the property of structural balance corresponds to the social community being splittable into two antagonistic factions, each containing only friends.',
	citation: 'Altafini C (2012) Dynamics of Opinion Forming in Structurally Balanced Social Networks. PLoS ONE 7(6): e38135. https://doi.org/10.1371/journal.pone.0038135'

 },
 {
 	header: 'Social Influence and the Collective Dynamics of Opinion Formation',
   	abstract: 'Social influence is the process by which individuals adapt their opinion, revise their beliefs, or change their behavior as a result of social interactions with other people. In our strongly interconnected society, social influence plays a prominent role in many self-organized phenomena such as herding in cultural markets, the spread of ideas and innovations, and the amplification of fears during epidemics. Yet, the mechanisms of opinion formation remain poorly understood, and existing physics-based models lack systematic empirical validation. Here, we report two controlled experiments showing how participants answering factual questions revise their initial judgments after being exposed to the opinion and confidence level of others. Based on the observation of 59 experimental subjects exposed to peer-opinion for 15 different items, we draw an influence map that describes the strength of peer influence during interactions. A simple process model derived from our observations demonstrates how opinions in a group of interacting people can converge or split over repeated interactions. In particular, we identify two major attractors of opinion: (i) the expert effect, induced by the presence of a highly confident individual in the group, and (ii) the majority effect, caused by the presence of a critical mass of laypeople sharing similar opinions. Additional simulations reveal the existence of a tipping point at which one attractor will dominate over the other, driving collective opinion in a given direction. These findings have implications for understanding the mechanisms of public opinion formation and managing conflicting situations in which self-confident and better informed minorities challenge the views of a large uninformed majority.',
 	citation: 'Moussaïd M, Kämmer JE, Analytis PP, Neth H (2013) Social Influence and the Collective Dynamics of Opinion Formation. PLoS ONE 8(11): e78433. https://doi.org/10.1371/journal.pone.0078433'
 },
 {
   header: 'Dynamics of opinion formation under majority rules on complex social networks.',
   abstract:'We study opinion dynamics on complex social networks where each individual holding a binary opinion on a certain subject may change her/his mind to match the opinion of the majority. Two rules of interactions between individuals, termed as classic majority and influence majority rules, respectively, are imposed on the social networks. The former rule allows each individual to adopt an opinion following a simple majority of her/his immediate neighbors, while the latter one lets each individual calculate the influence of each opinion and choose to follow the more influential one. In this calculation, the influences of different opinions are counted as the sum of the influences of their respective opinion holders in neighborhood area, where the influence of each individual is conveniently estimated as the number of social connections s/he has. Our study reveals that in densely-connected social networks, all individuals tend to converge to having a single global consensus. In sparsely-connected networks, however, the systems may exhibit rich properties where coexistence of different opinions, and more interestingly, multiple steady states of coexistence can be observed. Further studies reveal that low-degree and high-degree nodes may play different roles in formulating the final steady state, including multi-steady states, of the systems under different opinion evolution rules. Such observations would help understand the complex dynamics of opinion evolution and coexistence in social systems.',
   citation: 'Nguyen, V.X., Xiao, G., Xu, XJ. et al. Dynamics of opinion formation under majority rules on complex social networks. Sci Rep 10, 456 (2020). https://doi.org/10.1038/s41598-019-57086-3'
 }
];